name: Blackhawks Goal Monitor

on:
  schedule:
    # Runs every 5 minutes between 1:30 PM and 10:00 PM CST
    - cron: "30-59/5 19 * * *"
    - cron: "*/5 20-23 * * *"
    - cron: "*/5 0-4 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow for testing purposes

jobs:
  monitor-goals:
    if: github.ref == 'refs/heads/main' # Ensure this runs only on the main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests boto3

      - name: Run goal monitoring script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
          DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID }}
        run: |
          python run.py
